### ISSUE TITLE
Wallpaper modes "center" and "tile" not working as expected

### ISSUE THREAD

**Issue by Rolv-Apneseth** [danyspin97/wpaperd#69]
Hey @danyspin97, just having an issue with the latest changes and was wondering if you knew why. I'm seeing unexpected behaviour from the wallpaper modes, which I'll show with 2 images ([1](https://github.com/danyspin97/wpaperd/assets/69486699/4112e73a-6359-4252-9ea9-6b06a55b2d43) and [2](https://github.com/danyspin97/wpaperd/assets/69486699/11e6a6a0-539b-4328-941b-5d47bad78445)).

I usually leave the mode as `center` as I want it to cover the whole screen but keep the aspect ratio, but it seems to be tiling for "wide" images:

## Using `mode="tile"`
![tile_water](https://github.com/danyspin97/wpaperd/assets/69486699/dc96b624-6ed9-4060-916b-86370c981747)
![tile_wheat](https://github.com/danyspin97/wpaperd/assets/69486699/66215bbb-3b35-4dee-b6de-3dce39a169d2)

## Using `mode="center"`
![center_water](https://github.com/danyspin97/wpaperd/assets/69486699/72d249f3-900d-4cac-83c0-2ef1203b1859)
![center_wheat](https://github.com/danyspin97/wpaperd/assets/69486699/8193cf0a-8dfb-4f79-a759-cf56308ffb48)

**Comment by danyspin97** [comment]
Hey @Rolv-Apneseth, thank you for the issue. Yea, with the updates for the transitions, I had to change a bit the way that the wallpapers are drawn. Well... I was using pictures that which ratio was the same as my display and didn't notice the issues. I am already working on it since last week, I'll try to finish the fix by tomorrow (I am already halfway through it).

Nice bonus of the new way of drawing, transitions will work with `fit` mode.

**Comment by Rolv-Apneseth** [comment]
Awesome, thank you

**Comment by danyspin97** [comment]
In 0082898564dbcee1330237b914edf7d883dd81ec, modes `Center` and `Fit` (but the latter requires more testing) have been fixed. `Tile` is still broken, as I am trying to find the right equation to get the proportions of the image. `Fit` transitions have been overhauled and the code used for drawing is way simpler.

**Comment by Rolv-Apneseth** [comment]
That's great, thanks. `Center` looks good to me:

![fixed](https://github.com/danyspin97/wpaperd/assets/69486699/d0b5cff5-049d-49cb-80f9-7b9049d8c838)

---

Is `fit` supposed to distort images though? Probably causing a lot of issues with my wallpaper images being all sorts of different sizes haha

### Fit
![fit](https://github.com/danyspin97/wpaperd/assets/69486699/81851d2c-116a-4ccf-8912-b0cca9cde30f)

### Center
![center](https://github.com/danyspin97/wpaperd/assets/69486699/a1714d95-910b-4dbd-a8ca-c2ab96a87cfc)

**Comment by Rolv-Apneseth** [comment]
No worries, I only use `center` haha. [Here is that image](https://github.com/danyspin97/wpaperd/assets/69486699/2b6f9330-8fea-4c89-925d-362aa3a8bfd6) if it helps.

**Comment by danyspin97** [comment]
I finally managed to fix all modes! I have also tested the image you shared, and it should be working now!

Fixed by 86d8fb9f7e9bcca3bd3197652901ce5f8a37ecbe.

**Comment by Rolv-Apneseth** [comment]
Nice, most of them are working perfectly now. However, with the latest changes, I did find an image that is still getting stretched by `tile` ([this one](https://github.com/danyspin97/wpaperd/assets/69486699/5ca4403b-e5d5-407d-97a4-cf3b89ea2226)):

### Center
![center](https://github.com/danyspin97/wpaperd/assets/69486699/e4ef73ed-012f-40de-8655-ccacca0f7770)

### Fit
![fit](https://github.com/danyspin97/wpaperd/assets/69486699/53263dc8-9d05-4ff9-8768-9dc1d3296330)

### Tile
![tile](https://github.com/danyspin97/wpaperd/assets/69486699/473a533e-02f2-403b-a765-bf466dc091e6)

**Comment by danyspin97** [comment]
Right, that's definitely stretched xD cf662e5 should hopefully be the last fix!
