### ISSUE TITLE
Odd tile behavior

### ISSUE THREAD

**Issue by cdubthecoolcat** [danyspin97/wpaperd#77]
Tiling wallpapers on vertical monitors makes them look squished. Not sure if this is intended.

Example (latest git):
![2024-06-27-024154](https://github.com/danyspin97/wpaperd/assets/18389817/ed8828aa-e27b-4560-8a50-fef94a1c460c)

Expected: (release 1.0.1):
![2024-06-27-024211](https://github.com/danyspin97/wpaperd/assets/18389817/8f966212-df5c-44cc-a40f-ef09dbb6c1f8)

**Comment by danyspin97** [comment]
Hello @cdubthecoolcat and thank you for opening the issue!

That's definitely not correct... can you please share the wallpaper?

**Comment by cdubthecoolcat** [comment]
Sure thing.
![182  Eri Kamei](https://github.com/danyspin97/wpaperd/assets/18389817/d2b9349e-f721-4531-8620-209125a00455)

**Comment by danyspin97** [comment]
Can you please try with the latest version? I hope it is fixed now!

**Comment by cdubthecoolcat** [comment]
Unfortunately the problem persists, and now the image is rotated 90 degrees.

**Comment by danyspin97** [comment]
Are you using sway or hyprland as compositor?

**Comment by cdubthecoolcat** [comment]
Ahh I'm using Hyprland. I just tested it on sway and it seems to work fine. Must be a Hyprland issue then.

**Comment by danyspin97** [comment]
I fixied it on hyprland, went to sway and fixed it there just to break it on the former. Getting both right is not **easy**. 

I also found a bug in sway, so maybe this will lead me to find another issue? I will investigate more tomorrow. Thanks for testing!

**Comment by cdubthecoolcat** [comment]
No problem. Thanks for looking into this for me

**Comment by danyspin97** [comment]
I can confirm that hyprland and sway buffer rotations work in completely different way, creating this issue.

**Comment by danyspin97** [comment]
Upstream issue: https://github.com/hyprwm/Hyprland/issues/6754

**Comment by cdubthecoolcat** [comment]
Fixed in https://github.com/hyprwm/Hyprland/commit/1797319a0785cf9ae4f406d40bc27b032c6f5fb2
Although this also breaks latest release, git works fine though.
